name = "Coppermon Forge"
author = "Read"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc13b9959e4bd3e62b1b53040d27051cb46c402b8853656aa7eb1f58045875d4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
