name = "Coppermon Forge"
author = "Read"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "586c55c0f21988fbc0a2b020f3726ab729c62a23bfae2546ca7ab661fc5d5dcf"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
