name = "Coppermon Forge"
author = "Read"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd88b913649f515304ac6908797c9e90be55cd8afc927d89ec6c882392b5101"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
