name = "Coppermon Forge"
author = "Read"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0114f03eebb35e539295e51d02e30a9c04f5d2ac9a1d6434be36e277fa658edf"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
